
import com.excilys.ebi.gatling.core.Predef._
import com.excilys.ebi.gatling.http.Predef._
import com.excilys.ebi.gatling.jdbc.Predef._
import com.excilys.ebi.gatling.http.Headers.Names._
import akka.util.duration._
import bootstrap._
import assertions._

class AdminLogin extends Simulation {

	val httpConf = httpConfig
			.baseURL("https://impact-current.mperf.magento.com:443")
			.acceptHeader("*/*")
			.acceptEncodingHeader("gzip, deflate")
			.acceptLanguageHeader("en-US")
			.userAgentHeader("Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3)")


	val headers_1 = Map(
			"Accept" -> """application/x-ms-application, image/jpeg, application/xaml+xml, image/gif, image/pjpeg, application/x-ms-xbap, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/msword, */*""",
			"Connection" -> """Keep-Alive"""
	)

	val headers_2 = Map(
			"Accept" -> """application/x-ms-application, image/jpeg, application/xaml+xml, image/gif, image/pjpeg, application/x-ms-xbap, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/msword, */*""",
			"Cache-Control" -> """no-cache""",
			"Connection" -> """Keep-Alive""",
			"Content-Type" -> """application/x-www-form-urlencoded"""
	)

	val headers_3 = Map(
			"Connection" -> """Keep-Alive"""
	)


	val scn = scenario("Scenario Name")
		.exec(http("request_1")
					.get("/admin/")
					.headers(headers_1)
			)
		.pause(13)
		.exec(http("request_2")
					.post("/admin/")
					.headers(headers_2)
						.param("""form_key""", """zB2ESfILOOojT5bM""")
						.param("""login[username]""", """admin""")
						.param("""dummy""", """""")
						.param("""login[password]""", """123123q""")
			)
		.pause(2)
		.exec(http("request_3")
					.get("/js/calendar/calendar-win2k-1.css")
					.headers(headers_3)
			)
		.pause(40 milliseconds)
		.exec(http("request_4")
					.get("/skin/adminhtml/default/default/xmlconnect/boxes.css")
					.headers(headers_3)
			)
		.exec(http("request_5")
					.get("/skin/adminhtml/default/default/print.css")
					.headers(headers_3)
			)
		.exec(http("request_6")
					.get("/skin/adminhtml/default/default/menu.css")
					.headers(headers_3)
			)
		.exec(http("request_7")
					.get("/skin/adminhtml/default/default/custom.css")
					.headers(headers_3)
			)
		.pause(596 milliseconds)
		.exec(http("request_8")
					.get("/js/mage/adminhtml/hash.js")
					.headers(headers_3)
			)
		.exec(http("request_9")
					.get("/js/mage/adminhtml/events.js")
					.headers(headers_3)
			)
		.exec(http("request_10")
					.get("/js/mage/adminhtml/loader.js")
					.headers(headers_3)
			)
		.pause(191 milliseconds)
		.exec(http("request_11")
					.get("/js/prototype/window.js")
					.headers(headers_3)
			)
		.pause(34 milliseconds)
		.exec(http("request_12")
					.get("/js/mage/adminhtml/grid.js")
					.headers(headers_3)
			)
		.pause(375 milliseconds)
		.exec(http("request_13")
					.get("/js/mage/adminhtml/tabs.js")
					.headers(headers_3)
			)
		.exec(http("request_14")
					.get("/js/mage/adminhtml/accordion.js")
					.headers(headers_3)
			)
		.pause(111 milliseconds)
		.exec(http("request_15")
					.get("/js/mage/adminhtml/tools.js")
					.headers(headers_3)
			)
		.pause(86 milliseconds)
		.exec(http("request_16")
					.get("/js/mage/adminhtml/uploader.js")
					.headers(headers_3)
			)
		.pause(242 milliseconds)
		.exec(http("request_17")
					.get("/js/mage/adminhtml/product.js")
					.headers(headers_3)
			)
		.pause(160 milliseconds)
		.exec(http("request_18")
					.get("/js/calendar/calendar-setup.js")
					.headers(headers_3)
			)
		.pause(317 milliseconds)
		.exec(http("request_19")
					.get("/js/calendar/calendar.js")
					.headers(headers_3)
			)
		.pause(627 milliseconds)
		.exec(http("request_20")
					.get("/skin/adminhtml/default/enterprise/images/ajax-loader.gif")
					.headers(headers_3)
			)
		.exec(http("request_21")
					.get("/skin/adminhtml/default/enterprise/images/logo.gif")
					.headers(headers_3)
			)
		.exec(http("request_22")
					.get("/skin/adminhtml/default/enterprise/images/header_top_bg.gif")
					.headers(headers_3)
			)
		.pause(12 milliseconds)
		.exec(http("request_23")
					.get("/skin/adminhtml/default/default/images/nav1_bg.gif")
					.headers(headers_3)
			)
		.exec(http("request_24")
					.get("/skin/adminhtml/default/default/images/nav1_sep.gif")
					.headers(headers_3)
			)
		.pause(584 milliseconds)
		.exec(http("request_25")
					.get("/skin/adminhtml/default/default/images/nav2_li_bg.png")
					.headers(headers_3)
			)
		.exec(http("request_26")
					.get("/skin/adminhtml/default/default/images/nav3_bg.png")
					.headers(headers_3)
			)
		.exec(http("request_27")
					.get("/skin/adminhtml/default/default/images/nav2_last_li_bg.png")
					.headers(headers_3)
			)
		.pause(17 milliseconds)
		.exec(http("request_28")
					.get("/skin/adminhtml/default/enterprise/images/fam_help.gif")
					.headers(headers_3)
			)
		.exec(http("request_29")
					.get("/skin/adminhtml/default/default/images/nav1_active.gif")
					.headers(headers_3)
			)
		.pause(575 milliseconds)
		.exec(http("request_30")
					.get("/skin/adminhtml/default/default/images/nav2_link_bg.gif")
					.headers(headers_3)
			)
		.exec(http("request_31")
					.get("/skin/adminhtml/default/default/images/nav2_parent_arrow.gif")
					.headers(headers_3)
			)
		.exec(http("request_32")
					.get("/skin/adminhtml/default/enterprise/images/simple_container_bg.gif")
					.headers(headers_3)
			)
		.pause(23 milliseconds)
		.exec(http("request_33")
					.get("/skin/adminhtml/default/enterprise/images/sort_row_bg.gif")
					.headers(headers_3)
			)
		.exec(http("request_34")
					.get("/skin/adminhtml/default/enterprise/images/i_question-mark.png")
					.headers(headers_3)
			)
		.pause(569 milliseconds)
		.exec(http("request_35")
					.get("/skin/adminhtml/default/enterprise/images/horiz_tabs_ul_bg.gif")
					.headers(headers_3)
			)
		.exec(http("request_36")
					.get("/skin/adminhtml/default/enterprise/images/varien_logo.gif")
					.headers(headers_3)
			)
		.exec(http("request_37")
					.get("/skin/adminhtml/default/enterprise/images/ajax-loader-tr.gif")
					.headers(headers_3)
			)
		.pause(15 milliseconds)
		.exec(http("request_38")
					.get("/skin/adminhtml/default/enterprise/images/blank.gif")
					.headers(headers_3)
			)
		.exec(http("request_39")
					.get("/skin/adminhtml/default/enterprise/images/footer_bg.gif")
					.headers(headers_3)
			)

	setUp(scn.users(1).protocolConfig(httpConf))
}